// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: financials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSecSyncStatus = `-- name: GetSecSyncStatus :one
SELECT
    c.ticker,
    ss.status,
    ss.last_error,
    ss.updated_at
FROM companies AS c
JOIN sync_status AS ss ON ss.company_id = c.id
WHERE UPPER(c.ticker) = UPPER($1::text)
  AND ss.task_type = 'SEC_SYNC'
LIMIT 1
`

type GetSecSyncStatusRow struct {
	Ticker    string             `json:"ticker"`
	Status    string             `json:"status"`
	LastError pgtype.Text        `json:"last_error"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSecSyncStatus(ctx context.Context, ticker string) (GetSecSyncStatusRow, error) {
	row := q.db.QueryRow(ctx, getSecSyncStatus, ticker)
	var i GetSecSyncStatusRow
	err := row.Scan(
		&i.Ticker,
		&i.Status,
		&i.LastError,
		&i.UpdatedAt,
	)
	return i, err
}

const listFinancialMetricSnapshots = `-- name: ListFinancialMetricSnapshots :many
SELECT
    c.ticker,
    c.cik,
    c.name AS company_name,
    f.form_type,
    f.period_end_date,
    f.filed_at,
    f.accession_number,
    fm.base_metrics,
    fm.derived_metrics,
    fm.updated_at
FROM companies AS c
JOIN filings AS f ON f.company_id = c.id
JOIN financial_metrics AS fm ON fm.filing_id = f.id
WHERE UPPER(c.ticker) = UPPER($1::text)
ORDER BY f.period_end_date DESC, f.filed_at DESC
LIMIT 80
`

type ListFinancialMetricSnapshotsRow struct {
	Ticker          string             `json:"ticker"`
	Cik             string             `json:"cik"`
	CompanyName     string             `json:"company_name"`
	FormType        string             `json:"form_type"`
	PeriodEndDate   pgtype.Date        `json:"period_end_date"`
	FiledAt         pgtype.Date        `json:"filed_at"`
	AccessionNumber string             `json:"accession_number"`
	BaseMetrics     []byte             `json:"base_metrics"`
	DerivedMetrics  []byte             `json:"derived_metrics"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListFinancialMetricSnapshots(ctx context.Context, ticker string) ([]ListFinancialMetricSnapshotsRow, error) {
	rows, err := q.db.Query(ctx, listFinancialMetricSnapshots, ticker)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFinancialMetricSnapshotsRow{}
	for rows.Next() {
		var i ListFinancialMetricSnapshotsRow
		if err := rows.Scan(
			&i.Ticker,
			&i.Cik,
			&i.CompanyName,
			&i.FormType,
			&i.PeriodEndDate,
			&i.FiledAt,
			&i.AccessionNumber,
			&i.BaseMetrics,
			&i.DerivedMetrics,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
