// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Master company registry for SEC-tracked issuers.
type Company struct {
	// Internal system identifier.
	ID pgtype.UUID `json:"id"`
	// Stock symbol used as the primary lookup handle (for example AAPL).
	Ticker string `json:"ticker"`
	// 10-digit SEC identifier that preserves leading zeros.
	Cik string `json:"cik"`
	// Full legal name of the corporation.
	Name string `json:"name"`
	// Broad economic sector classification.
	Sector pgtype.Text `json:"sector"`
	// True to enable automated background scraping for the company.
	IsActive bool `json:"is_active"`
	// Timestamp when the company row was created.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when the company row was last updated.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Normalized SEC filing records associated with tracked companies.
type Filing struct {
	// Unique filing document identifier.
	ID pgtype.UUID `json:"id"`
	// Reference to the parent company in the companies table.
	CompanyID pgtype.UUID `json:"company_id"`
	// Report type such as 10-K or 10-Q.
	Type string `json:"type"`
	// Calendar year represented by the filing.
	FiscalYear int32 `json:"fiscal_year"`
	// Fiscal period label such as FY, Q1, or Q2.
	Period string `json:"period"`
	// SEC official receipt number used for deduplication.
	AccessionNum string `json:"accession_num"`
	// Date the report was officially published.
	FiledAt pgtype.Date `json:"filed_at"`
	// Timestamp when the filing row was ingested.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// 10-digit SEC identifier duplicated for direct filing upserts.
	Cik string `json:"cik"`
	// Normalized SEC filing type such as 10-K or 10-Q.
	FormType string `json:"form_type"`
	// Reporting period end date used for filing-level idempotency.
	PeriodEndDate pgtype.Date `json:"period_end_date"`
	// SEC accession number preserved for traceability.
	AccessionNumber string `json:"accession_number"`
	// Timestamp when the filing registry row was last updated.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Structured financial payloads extracted from a single filing.
type FinancialMetric struct {
	// Unique data record identifier.
	ID pgtype.UUID `json:"id"`
	// Reference to filings, with exactly one metrics row per filing.
	FilingID pgtype.UUID `json:"filing_id"`
	// JSONB super-dictionary containing parsed financial data such as revenue, EPS, assets, and liabilities.
	Metrics []byte `json:"metrics"`
	// Timestamp when the metrics payload was ingested.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Immutable standardized SEC base facts stored in wide-format JSONB.
	BaseMetrics []byte `json:"base_metrics"`
	// Internal derived calculations stored separately from SEC source DNA.
	DerivedMetrics []byte `json:"derived_metrics"`
	// Timestamp when the metrics payload was last updated.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Sync tracking rows for scrape, parse, and persistence tasks.
type SyncStatus struct {
	// Auto-incrementing log identifier for sync tracking.
	ID int64 `json:"id"`
	// Reference to the company currently being processed.
	CompanyID pgtype.UUID `json:"company_id"`
	// Current sync task type such as SCRAPE, PARSE, or UPSERT.
	TaskType string `json:"task_type"`
	// Task state such as PENDING, IN_PROGRESS, SUCCESS, or FAILED.
	Status string `json:"status"`
	// Detailed error message or stack trace when a sync task fails.
	LastError pgtype.Text `json:"last_error"`
	// Timestamp when the sync status row was created.
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	// Timestamp when the sync status row was last updated.
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}
