// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetSecSyncStatus(ctx context.Context, ticker string) (GetSecSyncStatusRow, error)
	ListFinancialMetricSnapshots(ctx context.Context, ticker string) ([]ListFinancialMetricSnapshotsRow, error)
}

var _ Querier = (*Queries)(nil)
